import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  return (
    <div className = {styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <div>
          <Image alt = 'logo' src = {'/images/SC-Icon-Black.png'} width = {50} height = {50}/>
          <br/>
          <nav className = {styles.nav}>
            
            <h1></h1>
            <h1>S'CELO CEDRICK <br/>MKHWANAZI</h1>
          </nav>
        </div>
      
      </header>
      
      <main className={styles.main}>
        {data.map(ind => <a key = {ind.id} href = {'/index/${ind.id}'}>
          <Image width = {400} height = {300} alt = {ind.title} src ={ind.image}/> <h2>{ind.title}</h2>
          <p>{ind.description}</p>
        </a>)}
      <div className={styles.image}>
          <img />
          
        </div>

          <h1>
            
          </h1>

          <p>

          </p>
        
        
      </main>
        
          <footer className={styles.footer}>
            <p> &copy; 2023 Scelo Mkhwanazi </p>
          </footer>
        
    </div>
    
    
  )
}

export async function getServerSideProps(){
  const {index_categories} = await import('/data/data.json');
  console.log(index_categories);
  return{
    props:{
      data: index_categories,
    },
  };
}


